[package]
name = "nes_by_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes_core = {path = "./nes_core"}
sdl2 = "0.35.2"
rand = "0.8.5"